siteTitle = "Blog by krahser"
siteDescr = "Tecnología para compartir"
siteAuthor = "Aldo María Vizcaino"

siteTelegramUrl = ""
siteTwitterUrl = ""
siteGithubUrl = "https://github.com/krahser"
siteEmailUrl = ""
siteRssUrl = ""
siteVkUrl = ""

googleAnalyticsId = "UA-49097633-2"

linkPrefix = ""
